// Scenario construction mirroring scenario.ScenarioConfig's JSON shape.

export type CC = 'cubic' | 'bbr'

export interface LabCfg {
  rateMbps: number
  owdMs: number
  lossPct: number // percent, converted to a [0,1) fraction in the JSON
  qlimPkts: number
}

// Few-core machines are phones and small laptops: Go-wasm sim throughput
// there is roughly an order of magnitude below native, so they also get a
// 4× lighter default link (buffer rescaled to keep the same ~1×BDP shape).
// The sliders still reach the full range.
export const SMALL_MACHINE =
  (typeof navigator !== 'undefined' ? navigator.hardwareConcurrency || 4 : 4) < 8

export const HEAVY_CFG: LabCfg = { rateMbps: 100, owdMs: 20, lossPct: 0, qlimPkts: 350 }
export const LITE_CFG: LabCfg = { rateMbps: 25, owdMs: 20, lossPct: 0, qlimPkts: 90 }
export const DEFAULT_CFG: LabCfg = SMALL_MACHINE ? LITE_CFG : HEAVY_CFG

const cfgEq = (a: LabCfg, b: LabCfg) =>
  a.rateMbps === b.rateMbps && a.owdMs === b.owdMs && a.lossPct === b.lossPct && a.qlimPkts === b.qlimPkts

// Precomputed streams for the default scenarios, generated by `make
// lab-precomp` from the native binary. Determinism makes them
// byte-identical to a live wasm run of the same scenario, so the page
// renders instantly at defaults and only pays for wasm when a slider
// leaves them. Returns null when no precomputed stream matches.
export function fig1Precomp(cc: CC, cfg: LabCfg): string | null {
  if (cfgEq(cfg, HEAVY_CFG)) return `/sim/pre/fig1-${cc}.bin`
  if (cfgEq(cfg, LITE_CFG)) return `/sim/pre/fig1-${cc}-lite.bin`
  return null
}

export function fig2Precomp(cc: CC, lossPct: number): string | null {
  return lossPct === 0 ? `/sim/pre/fig2-${cc}.bin` : null
}

export const RUN_DUR_S = 30

export interface Derived {
  baseMs: number // base RTT
  bdpPkts: number // 1500-byte packets
  bdpBytes: number
  bufX: number // buffer in ×BDP
  cliff: number // inflight (×BDP) at which the tail-drop buffer is full
}

export function derive(cfg: LabCfg): Derived {
  const baseMs = 2 * cfg.owdMs
  const bdpBytes = (cfg.rateMbps * 1e6 / 8) * (baseMs / 1000)
  const bdpPkts = Math.max(4, bdpBytes / 1500)
  const bufX = cfg.qlimPkts / bdpPkts
  return { baseMs, bdpPkts, bdpBytes, bufX, cliff: 1 + bufX }
}

export function scenarioFor(cc: CC, cfg: LabCfg): object {
  return {
    seed: 7,
    dur_s: RUN_DUR_S,
    link: {
      rate_mbps: cfg.rateMbps,
      owd_ms: cfg.owdMs,
      loss: cfg.lossPct / 100,
      queue: { kind: 'taildrop', limit_pkts: Math.round(cfg.qlimPkts) },
    },
    flows: [{ cc, start_at_s: 0, app: { kind: 'bulk' } }],
    // The figures resample onto a 20 ms grid (series.toPts dt), so finer
    // sampling is pure stream weight — this cuts streams 20× vs the 1 ms
    // default, which is what makes shipping precomputed defaults viable.
    sample: { interval_ms: 20 },
  }
}

// The bandwidth-change experiment from the BBR paper (ACM Queue, figure 3):
// a 10-Mbps, 40-ms flow whose bottleneck doubles to 20 Mbps at t=20 s and
// drops back to 10 Mbps at t=40 s. Rate, delay, and buffer stay fixed —
// the figure's chrome (link-rate step path, lane ranges, step labels) is
// drawn to them — but wire loss is adjustable and either CC can run it.
export const BWSTEP_DUR_S = 60
export const BWSTEP_CFG: LabCfg = { rateMbps: 10, owdMs: 20, lossPct: 0, qlimPkts: 133 }

export function bwStepScenario(cc: CC, lossPct: number): object {
  return {
    ...scenarioFor(cc, { ...BWSTEP_CFG, lossPct }),
    dur_s: BWSTEP_DUR_S,
    events: [
      { at_s: 20, path: 'link.rate_mbps', value: 20 },
      { at_s: 40, path: 'link.rate_mbps', value: 10 },
    ],
  }
}
