// Scenario construction mirroring scenario.ScenarioConfig's JSON shape.

export type CC = 'cubic' | 'bbr' | 'naive'

// Mirrors naive.RateBps. The naive controller is intentionally fixed-rate;
// link sliders change the bottleneck, not the sender's offered load.
export const NAIVE_RATE_MBPS = 150

export interface LabCfg {
  rateMbps: number
  owdMs: number
  jitterMs: number // max extra delivery delay per packet, uniform, FIFO-preserving
  lossPct: number // percent, converted to a [0,1) fraction in the JSON
  qlimPkts: number
}

// Few-core machines are phones and small laptops: Go-wasm sim throughput
// there is roughly an order of magnitude below native, so they also get a
// 4× lighter default link (buffer rescaled to keep the same ~1×BDP shape).
// The sliders still reach the full range.
// Safari's Lockdown Mode (and some enterprise policies) removes the
// WebAssembly global entirely. Precomputed default streams don't need it —
// only live (off-default) simulation does, so gate the worker path on this
// instead of surfacing a raw ReferenceError from inside the worker.
export const WASM_OK = typeof WebAssembly !== 'undefined'

export const SMALL_MACHINE =
  (typeof navigator !== 'undefined' ? navigator.hardwareConcurrency || 4 : 4) < 8

// Default jitter is a deliberately low, realistic access-path value: enough
// for delay variance to exist (like the real internet) without dominating
// the figures.
export const HEAVY_CFG: LabCfg = { rateMbps: 100, owdMs: 20, jitterMs: 1, lossPct: 0, qlimPkts: 350 }
export const LITE_CFG: LabCfg = { rateMbps: 25, owdMs: 20, jitterMs: 1, lossPct: 0, qlimPkts: 90 }
export const DEFAULT_CFG: LabCfg = SMALL_MACHINE ? LITE_CFG : HEAVY_CFG

const cfgEq = (a: LabCfg, b: LabCfg) =>
  a.rateMbps === b.rateMbps && a.owdMs === b.owdMs && a.jitterMs === b.jitterMs &&
  a.lossPct === b.lossPct && a.qlimPkts === b.qlimPkts

// Precomputed streams for the default scenarios, generated by `make
// lab-precomp` from the native binary. Determinism makes them
// byte-identical to a live wasm run of the same scenario, so the page
// renders instantly at defaults and only pays for wasm when a slider
// leaves them. Returns null when no precomputed stream matches.
export function fig1Precomp(cc: CC, cfg: LabCfg): string | null {
  // Fig. 3's naive control is intentionally the canonical 150→100 Mbps
  // overload experiment rather than another slider-dependent comparison.
  if (cc === 'naive') return cfgEq(cfg, HEAVY_CFG) ? '/sim/pre/fig1-naive.bin' : null
  if (cfgEq(cfg, HEAVY_CFG)) return `/sim/pre/fig1-${cc}.bin`
  if (cfgEq(cfg, LITE_CFG)) return `/sim/pre/fig1-${cc}-lite.bin`
  return null
}

export function fig2Precomp(cc: CC, lossPct: number, jitterMs: number): string | null {
  return lossPct === 0 && jitterMs === 0 ? `/sim/pre/fig2-${cc}.bin` : null
}

export const RUN_DUR_S = 30

export interface Derived {
  baseMs: number // base RTT
  bdpPkts: number // 1500-byte packets
  bdpBytes: number
  bufX: number // buffer in ×BDP
  cliff: number // inflight (×BDP) at which the tail-drop buffer is full
}

export function derive(cfg: LabCfg): Derived {
  const baseMs = 2 * cfg.owdMs
  const bdpBytes = (cfg.rateMbps * 1e6 / 8) * (baseMs / 1000)
  const bdpPkts = Math.max(4, bdpBytes / 1500)
  const bufX = cfg.qlimPkts / bdpPkts
  return { baseMs, bdpPkts, bdpBytes, bufX, cliff: 1 + bufX }
}

export function scenarioFor(cc: CC, cfg: LabCfg): object {
  return {
    seed: 7,
    dur_s: RUN_DUR_S,
    link: {
      rate_mbps: cfg.rateMbps,
      owd_ms: cfg.owdMs,
      ...(cfg.jitterMs > 0 ? { jitter_ms: cfg.jitterMs } : {}),
      loss: cfg.lossPct / 100,
      queue: { kind: 'taildrop', limit_pkts: Math.round(cfg.qlimPkts) },
    },
    flows: [{ cc, start_at_s: 0, app: { kind: 'bulk' } }],
    // The figures resample onto a 20 ms grid (series.toPts dt), so finer
    // sampling is pure stream weight — this cuts streams 20× vs the 1 ms
    // default, which is what makes shipping precomputed defaults viable.
    // wire_stats adds compact cumulative enqueue/dequeue counters, an
    // arrival-burstiness record, and the sender's latest raw RTT sample per
    // window. Fig. 3 derives its particles and actual-RTT trace from that
    // telemetry without shipping the much larger per-packet event stream.
    sample: { interval_ms: 20, wire_stats: true },
  }
}

// The bandwidth-change experiment from the BBR paper (ACM Queue, figure 3):
// a 10-Mbps, 40-ms flow whose bottleneck doubles for 20 seconds. The paper's
// 20/40-second changes are shifted to 21/41 here so the deterministic BBR run
// is in CRUISE, rather than entering ProbeBW:UP on the exact up-step. Rate,
// delay, and buffer stay fixed — the figure's chrome is drawn to them — but
// wire loss and jitter are adjustable and either CC can run it.
export const BWSTEP_DUR_S = 60
export const BWSTEP_UP_S = 21
export const BWSTEP_DOWN_S = 41
// jitter 0 default: the precomputed streams reproduce the paper's clean-path
// experiment; the sliders opt into a dirtier path.
export const BWSTEP_CFG: LabCfg = { rateMbps: 10, owdMs: 20, jitterMs: 0, lossPct: 0, qlimPkts: 133 }

export function bwStepScenario(cc: CC, lossPct: number, jitterMs = 0): object {
  return {
    ...scenarioFor(cc, { ...BWSTEP_CFG, lossPct, jitterMs }),
    dur_s: BWSTEP_DUR_S,
    events: [
      { at_s: BWSTEP_UP_S, path: 'link.rate_mbps', value: 20 },
      { at_s: BWSTEP_DOWN_S, path: 'link.rate_mbps', value: 10 },
    ],
  }
}
